(in-package "ACL2")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; federal_save_act_consistency_audit.lisp  —  GENERATED by tools/gen_consistency_audit.py
;;
;; CONSISTENCY AUDIT of each party's trusted base (cf. Vero, arXiv:2608.13522 § 3.5).
;; For each party theory, every defstub gets a concrete toy-world definition
;; (aud-<party>-<name>), every core defun is re-defined over that world, and
;; every defaxiom / encapsulate constraint of the theory is restated over the
;; world and PROVED.  Certification of this book = the theory is satisfiable.
;; A failing theorem names an inconsistent axiom or a missing condition.
;; This book includes no party book and contains no defaxiom (neutral).
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; =========================================================================
;;; WORLD C: the challenger theory
;;; books: federal_save_act_core, federal_save_act_text_rules, federal_save_act_voting_text_rules, federal_save_act_facts, federal_save_act_scenario, federal_save_act_hinge_common, federal_save_act_hinge_discretionary, federal_save_act_challenger_model
;;; =========================================================================

;; --- 67 stub / signature definitions ---
(defun aud-c-personp (p) (if (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) t nil))
(defun aud-c-lawp (law) (if (equal law 'federal-save-act) t nil))
(defun aud-c-citizen-of-usp (p) (if (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) t nil))
(defun aud-c-eligible-voterp (p) (if (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) t nil))
(defun aud-c-voter-registration-applicationp (x) (if (equal x 'registration-attempt-a) t nil))
(defun aud-c-has-documentary-proofp (x) (declare (ignore x)) nil)
(defun aud-c-presents-documentary-proofp (p x) (declare (ignore p x)) nil)
(defun aud-c-has-real-id-indicating-citizenshipp (x) (declare (ignore x)) nil)
(defun aud-c-has-valid-us-passportp (x) (declare (ignore x)) nil)
(defun aud-c-has-military-id-with-us-birthp (x) (declare (ignore x)) nil)
(defun aud-c-has-govt-photo-id-showing-us-birthp (x) (declare (ignore x)) nil)
(defun aud-c-has-govt-photo-idp (x) (declare (ignore x)) nil)
(defun aud-c-has-certified-birth-certificatep (x) (declare (ignore x)) nil)
(defun aud-c-has-hospital-birth-recordp (x) (declare (ignore x)) nil)
(defun aud-c-has-final-adoption-decreep (x) (declare (ignore x)) nil)
(defun aud-c-has-consular-report-of-birth-abroadp (x) (declare (ignore x)) nil)
(defun aud-c-has-naturalization-certificatep (x) (declare (ignore x)) nil)
(defun aud-c-has-american-indian-card-kicp (x) (declare (ignore x)) nil)
(defun aud-c-protected-right-to-votep (cs p) (if (and (equal cs 'amend-v-equal-protection) (member-equal p '(citizen-a citizen-b citizen-c citizen-d))) t nil))
(defun aud-c-undue-burden-on-right-to-votep (law p) (declare (ignore law p)) (if t t nil))
(defun aud-c-valid-regulationp (law x) (declare (ignore law x)) (if nil t nil))
(defun aud-c-statute-denies-registrationp (law p x) (if (and (equal law 'federal-save-act) (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) (equal x 'registration-attempt-a) (equal p 'citizen-a)) t nil))
(defun aud-c-attempts-to-registerp (p x) (if (and (equal p 'citizen-a) (equal x 'registration-attempt-a)) t nil))
(defun aud-c-registers-by-mailp (p x) (declare (ignore p x)) nil)
(defun aud-c-registers-at-dmvp (p x) (declare (ignore p x)) nil)
(defun aud-c-alternative-process-availablep (p x) (declare (ignore p x)) (if t t nil))
(defun aud-c-alternative-process-approvedp (p x) (declare (ignore p x)) (if nil t nil))
(defun aud-c-signs-attestation-under-perjuryp (p) (declare (ignore p)) nil)
(defun aud-c-submits-other-evidencep (p) (declare (ignore p)) nil)
(defun aud-c-official-determines-citizenshipp (p) (declare (ignore p)) nil)
(defun aud-c-registered-voterp (p) (if (member-equal p '(citizen-b citizen-c citizen-d)) t nil))
(defun aud-c-verified-noncitizen-informationp (p) (if (equal p 'citizen-b) t nil))
(defun aud-c-adequate-notice-before-removalp (p) (declare (ignore p)) nil)
(defun aud-c-opportunity-to-be-heardp (p) (declare (ignore p)) nil)
(defun aud-c-statute-removes-registrantp (law p) (if (and (equal law 'federal-save-act) (member-equal p '(citizen-b citizen-c citizen-d)) (equal p 'citizen-b)) t nil))
(defun aud-c-removal-procedure-evenhandedp (law) (declare (ignore law)) nil)
(defun aud-c-criminal-penalty-for-official-assistancep (official) (declare (ignore official)) nil)
(defun aud-c-criminal-penalty-for-registering-without-proofp (official p) (declare (ignore official p)) nil)
(defun aud-c-document-acquisition-costp (p) (declare (ignore p)) (if t t nil))
(defun aud-c-cost-functions-as-poll-taxp (law p) (declare (ignore law p)) (if t t nil))
(defun aud-c-lacks-qualifying-documents-through-no-faultp (p) (declare (ignore p)) (if t t nil))
(defun aud-c-cannot-obtain-qualifying-documents-without-material-burdenp (p) (declare (ignore p)) (if t t nil))
(defun aud-c-alternative-process-discretionary-forp (p x) (declare (ignore p x)) (if t t nil))
(defun aud-c-substantial-risk-of-erroneous-denialp (law p) (declare (ignore law p)) (if t t nil))
(defun aud-c-severe-burden-on-plaintiffp (law p) (declare (ignore law p)) (if t t nil))
(defun aud-c-important-government-interestp (law) (declare (ignore law)) nil)
(defun aud-c-election-integrity-interestp (law) (declare (ignore law)) nil)
(defun aud-c-registration-procedure-evenhandedp (law) (declare (ignore law)) nil)
(defun aud-c-documentary-proof-requirement-rationally-connectedp (law) (declare (ignore law)) nil)
(defun aud-c-reasonable-registration-requirementp (law) (declare (ignore law)) nil)
(defun aud-c-adequate-alternative-processp (law) (declare (ignore law)) nil)
(defun aud-c-burden-not-severep (law p) (declare (ignore law p)) nil)
(defun aud-c-ballotp (b) (if (member-equal b '(ballot-c ballot-d)) t nil))
(defun aud-c-votes-in-personp (p b) (if (or (and (equal p 'citizen-c) (equal b 'ballot-c)) (and (equal p 'citizen-d) (equal b 'ballot-d))) t nil))
(defun aud-c-presents-valid-photo-idp (p b) (declare (ignore p b)) nil)
(defun aud-c-cures-within-deadlinep (p b) (if (and (equal p 'citizen-d) (equal b 'ballot-d)) t nil))
(defun aud-c-statute-denies-regular-ballotp (law p b) (if (and (equal law 'federal-save-act) (member-equal p '(citizen-b citizen-c citizen-d)) (member-equal b '(ballot-c ballot-d))) t nil))
(defun aud-c-cannot-obtain-valid-photo-id-without-material-burdenp (p) (declare (ignore p)) (if t t nil))
(defun aud-c-photo-id-requirement-evenhandedp (law) (declare (ignore law)) nil)
(defun aud-c-provisional-cure-adequatep (law) (declare (ignore law)) nil)
(defun aud-c-attestation-evidence-satisfies-standardsp (p x) (declare (ignore p x)) (if nil t nil))
(defun aud-c-official-discretionary-denialp (p x) (declare (ignore p x)) (if t t nil))
(defun aud-c-challenger-right-to-vote-establishedp (p) (if (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) t nil))
(defun aud-c-challenger-undue-burden-establishedp (law p) (declare (ignore p)) (if (equal law 'federal-save-act) t nil))
(defun aud-c-challenger-regulation-invalidp (law x) (declare (ignore x)) (if (equal law 'federal-save-act) t nil))
(defun aud-c-challenger-removal-due-process-violationp (law p) (declare (ignore p)) (if (equal law 'federal-save-act) t nil))
(defun aud-c-challenger-voting-burden-establishedp (law p) (declare (ignore p)) (if (equal law 'federal-save-act) t nil))

;; --- 12 core definitions over the world ---
(defun aud-c-has-supporting-documentp (x)
  (or (aud-c-has-certified-birth-certificatep x) (aud-c-has-hospital-birth-recordp x) (aud-c-has-final-adoption-decreep x) (aud-c-has-consular-report-of-birth-abroadp x) (aud-c-has-naturalization-certificatep x) (aud-c-has-american-indian-card-kicp x)))
(defun aud-c-has-govt-photo-id-with-supporting-docp (x)
  (and (aud-c-has-govt-photo-idp x) (aud-c-has-supporting-documentp x)))
(defun aud-c-has-any-qualifying-documentp (p)
  (or (aud-c-has-real-id-indicating-citizenshipp p) (aud-c-has-valid-us-passportp p) (aud-c-has-military-id-with-us-birthp p) (aud-c-has-govt-photo-id-showing-us-birthp p) (aud-c-has-govt-photo-id-with-supporting-docp p)))
(defun aud-c-qualified-federal-voterp (p)
  (and (aud-c-personp p) (aud-c-citizen-of-usp p) (aud-c-eligible-voterp p)))
(defun aud-c-registration-transactionp (p x)
  (and (aud-c-personp p) (aud-c-voter-registration-applicationp x) (aud-c-attempts-to-registerp p x)))
(defun aud-c-save-act-denial-triggerp (p x)
  (and (aud-c-registration-transactionp p x) (not (aud-c-presents-documentary-proofp p x)) (not (aud-c-alternative-process-approvedp p x))))
(defun aud-c-constitutional-conflict-conditionp (law constitution-section p x)
  (and (aud-c-lawp law) (aud-c-qualified-federal-voterp p) (aud-c-protected-right-to-votep constitution-section p) (aud-c-registration-transactionp p x) (aud-c-statute-denies-registrationp law p x) (not (aud-c-valid-regulationp law x))))
(defun aud-c-removal-transactionp (p)
  (and (aud-c-personp p) (aud-c-registered-voterp p)))
(defun aud-c-constitutional-removal-conflict-conditionp (law constitution-section p)
  (and (aud-c-lawp law) (aud-c-qualified-federal-voterp p) (aud-c-protected-right-to-votep constitution-section p) (aud-c-removal-transactionp p) (aud-c-statute-removes-registrantp law p) (not (aud-c-valid-regulationp law p))))
(defun aud-c-voting-transactionp (p b)
  (and (aud-c-personp p) (aud-c-registered-voterp p) (aud-c-ballotp b) (aud-c-votes-in-personp p b)))
(defun aud-c-ballot-not-countedp (law p b)
  (and (aud-c-statute-denies-regular-ballotp law p b) (not (aud-c-cures-within-deadlinep p b))))
(defun aud-c-constitutional-voting-conflict-conditionp (law constitution-section p b)
  (and (aud-c-lawp law) (aud-c-qualified-federal-voterp p) (aud-c-protected-right-to-votep constitution-section p) (aud-c-voting-transactionp p b) (aud-c-ballot-not-countedp law p b) (not (aud-c-valid-regulationp law b))))

;; --- 51 audited propositions (7 encapsulate constraints, 44 defaxioms) ---
;; constraint hinge-evidence-type  [federal_save_act_hinge_common]
(defthm aud-c-hinge-evidence-type
  (booleanp (aud-c-attestation-evidence-satisfies-standardsp p x))
  :rule-classes nil)
;; constraint hinge-denial-type  [federal_save_act_hinge_common]
(defthm aud-c-hinge-denial-type
  (booleanp (aud-c-official-discretionary-denialp p x))
  :rule-classes nil)
;; constraint challenger-fundamental-right-rule  [federal_save_act_challenger_model]
(defthm aud-c-challenger-fundamental-right-rule
  (implies (aud-c-qualified-federal-voterp p) (aud-c-challenger-right-to-vote-establishedp p))
  :rule-classes nil)
;; constraint challenger-documentary-proof-is-undue-burden  [federal_save_act_challenger_model]
(defthm aud-c-challenger-documentary-proof-is-undue-burden
  (implies (and (aud-c-qualified-federal-voterp p) (not (aud-c-has-documentary-proofp p)) (aud-c-lacks-qualifying-documents-through-no-faultp p) (aud-c-cannot-obtain-qualifying-documents-without-material-burdenp p)) (aud-c-challenger-undue-burden-establishedp 'federal-save-act p))
  :rule-classes nil)
;; constraint challenger-undue-burden-defeats-regulation  [federal_save_act_challenger_model]
(defthm aud-c-challenger-undue-burden-defeats-regulation
  (implies (and (aud-c-challenger-undue-burden-establishedp 'federal-save-act p) (aud-c-voter-registration-applicationp x)) (aud-c-challenger-regulation-invalidp 'federal-save-act x))
  :rule-classes nil)
;; constraint challenger-removal-without-process-is-violation  [federal_save_act_challenger_model]
(defthm aud-c-challenger-removal-without-process-is-violation
  (implies (and (aud-c-qualified-federal-voterp p) (aud-c-registered-voterp p) (aud-c-statute-removes-registrantp 'federal-save-act p) (not (aud-c-adequate-notice-before-removalp p)) (not (aud-c-opportunity-to-be-heardp p))) (aud-c-challenger-removal-due-process-violationp 'federal-save-act p))
  :rule-classes nil)
;; constraint challenger-uncounted-ballot-is-severe-burden  [federal_save_act_challenger_model]
(defthm aud-c-challenger-uncounted-ballot-is-severe-burden
  (implies (and (aud-c-qualified-federal-voterp p) (aud-c-registered-voterp p) (aud-c-ballot-not-countedp 'federal-save-act p b) (aud-c-cannot-obtain-valid-photo-id-without-material-burdenp p)) (aud-c-challenger-voting-burden-establishedp 'federal-save-act p))
  :rule-classes nil)
;; axiom text-save-act-documentary-proof-requirement  [federal_save_act_text_rules]
(defthm aud-c-text-save-act-documentary-proof-requirement
  (implies (and (aud-c-personp p) (aud-c-voter-registration-applicationp x) (aud-c-attempts-to-registerp p x) (not (aud-c-presents-documentary-proofp p x)) (not (aud-c-alternative-process-approvedp p x))) (aud-c-statute-denies-registrationp 'federal-save-act p x))
  :rule-classes nil)
;; axiom text-save-act-removal-upon-verified-information  [federal_save_act_text_rules]
(defthm aud-c-text-save-act-removal-upon-verified-information
  (implies (and (aud-c-personp p) (aud-c-registered-voterp p) (aud-c-verified-noncitizen-informationp p)) (aud-c-statute-removes-registrantp 'federal-save-act p))
  :rule-classes nil)
;; axiom text-photo-id-required-for-regular-ballot  [federal_save_act_voting_text_rules]
(defthm aud-c-text-photo-id-required-for-regular-ballot
  (implies (and (aud-c-personp p) (aud-c-registered-voterp p) (aud-c-ballotp b) (aud-c-votes-in-personp p b) (not (aud-c-presents-valid-photo-idp p b))) (aud-c-statute-denies-regular-ballotp 'federal-save-act p b))
  :rule-classes nil)
;; axiom text-save-act-is-law  [federal_save_act_facts]
(defthm aud-c-text-save-act-is-law
  (aud-c-lawp 'federal-save-act)
  :rule-classes nil)
;; axiom text-documentary-proof-from-qualifying-documents  [federal_save_act_facts]
(defthm aud-c-text-documentary-proof-from-qualifying-documents
  (implies (aud-c-has-any-qualifying-documentp p) (aud-c-has-documentary-proofp p))
  :rule-classes nil)
;; axiom scenario-person  [federal_save_act_scenario]
(defthm aud-c-scenario-person
  (aud-c-personp 'citizen-a)
  :rule-classes nil)
;; axiom scenario-citizen  [federal_save_act_scenario]
(defthm aud-c-scenario-citizen
  (aud-c-citizen-of-usp 'citizen-a)
  :rule-classes nil)
;; axiom scenario-eligible  [federal_save_act_scenario]
(defthm aud-c-scenario-eligible
  (aud-c-eligible-voterp 'citizen-a)
  :rule-classes nil)
;; axiom scenario-application  [federal_save_act_scenario]
(defthm aud-c-scenario-application
  (aud-c-voter-registration-applicationp 'registration-attempt-a)
  :rule-classes nil)
;; axiom scenario-attempts-to-register  [federal_save_act_scenario]
(defthm aud-c-scenario-attempts-to-register
  (aud-c-attempts-to-registerp 'citizen-a 'registration-attempt-a)
  :rule-classes nil)
;; axiom scenario-no-documentary-proof  [federal_save_act_scenario]
(defthm aud-c-scenario-no-documentary-proof
  (not (aud-c-has-documentary-proofp 'citizen-a))
  :rule-classes nil)
;; axiom scenario-b-person  [federal_save_act_scenario]
(defthm aud-c-scenario-b-person
  (aud-c-personp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-citizen  [federal_save_act_scenario]
(defthm aud-c-scenario-b-citizen
  (aud-c-citizen-of-usp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-eligible  [federal_save_act_scenario]
(defthm aud-c-scenario-b-eligible
  (aud-c-eligible-voterp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-registered  [federal_save_act_scenario]
(defthm aud-c-scenario-b-registered
  (aud-c-registered-voterp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-verified-noncitizen-information  [federal_save_act_scenario]
(defthm aud-c-scenario-b-verified-noncitizen-information
  (aud-c-verified-noncitizen-informationp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-no-notice  [federal_save_act_scenario]
(defthm aud-c-scenario-b-no-notice
  (not (aud-c-adequate-notice-before-removalp 'citizen-b))
  :rule-classes nil)
;; axiom scenario-b-no-hearing  [federal_save_act_scenario]
(defthm aud-c-scenario-b-no-hearing
  (not (aud-c-opportunity-to-be-heardp 'citizen-b))
  :rule-classes nil)
;; axiom scenario-c-person  [federal_save_act_scenario]
(defthm aud-c-scenario-c-person
  (aud-c-personp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-citizen  [federal_save_act_scenario]
(defthm aud-c-scenario-c-citizen
  (aud-c-citizen-of-usp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-eligible  [federal_save_act_scenario]
(defthm aud-c-scenario-c-eligible
  (aud-c-eligible-voterp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-registered  [federal_save_act_scenario]
(defthm aud-c-scenario-c-registered
  (aud-c-registered-voterp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-ballot  [federal_save_act_scenario]
(defthm aud-c-scenario-c-ballot
  (aud-c-ballotp 'ballot-c)
  :rule-classes nil)
;; axiom scenario-c-votes-in-person  [federal_save_act_scenario]
(defthm aud-c-scenario-c-votes-in-person
  (aud-c-votes-in-personp 'citizen-c 'ballot-c)
  :rule-classes nil)
;; axiom scenario-c-no-valid-photo-id  [federal_save_act_scenario]
(defthm aud-c-scenario-c-no-valid-photo-id
  (not (aud-c-presents-valid-photo-idp 'citizen-c 'ballot-c))
  :rule-classes nil)
;; axiom scenario-c-no-cure  [federal_save_act_scenario]
(defthm aud-c-scenario-c-no-cure
  (not (aud-c-cures-within-deadlinep 'citizen-c 'ballot-c))
  :rule-classes nil)
;; axiom scenario-d-person  [federal_save_act_scenario]
(defthm aud-c-scenario-d-person
  (aud-c-personp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-citizen  [federal_save_act_scenario]
(defthm aud-c-scenario-d-citizen
  (aud-c-citizen-of-usp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-eligible  [federal_save_act_scenario]
(defthm aud-c-scenario-d-eligible
  (aud-c-eligible-voterp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-registered  [federal_save_act_scenario]
(defthm aud-c-scenario-d-registered
  (aud-c-registered-voterp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-ballot  [federal_save_act_scenario]
(defthm aud-c-scenario-d-ballot
  (aud-c-ballotp 'ballot-d)
  :rule-classes nil)
;; axiom scenario-d-votes-in-person  [federal_save_act_scenario]
(defthm aud-c-scenario-d-votes-in-person
  (aud-c-votes-in-personp 'citizen-d 'ballot-d)
  :rule-classes nil)
;; axiom scenario-d-no-valid-photo-id  [federal_save_act_scenario]
(defthm aud-c-scenario-d-no-valid-photo-id
  (not (aud-c-presents-valid-photo-idp 'citizen-d 'ballot-d))
  :rule-classes nil)
;; axiom scenario-d-cures  [federal_save_act_scenario]
(defthm aud-c-scenario-d-cures
  (aud-c-cures-within-deadlinep 'citizen-d 'ballot-d)
  :rule-classes nil)
;; axiom semantic-b-discretionary-denial  [federal_save_act_hinge_discretionary]
(defthm aud-c-semantic-b-discretionary-denial
  (implies (aud-c-official-discretionary-denialp p x) (not (aud-c-alternative-process-approvedp p x)))
  :rule-classes nil)
;; axiom challenger-bridge-right-to-vote  [federal_save_act_challenger_model]
(defthm aud-c-challenger-bridge-right-to-vote
  (implies (aud-c-challenger-right-to-vote-establishedp p) (aud-c-protected-right-to-votep 'amend-v-equal-protection p))
  :rule-classes nil)
;; axiom challenger-bridge-regulation-invalid  [federal_save_act_challenger_model]
(defthm aud-c-challenger-bridge-regulation-invalid
  (implies (aud-c-challenger-regulation-invalidp 'federal-save-act x) (not (aud-c-valid-regulationp 'federal-save-act x)))
  :rule-classes nil)
;; axiom challenger-scenario-no-presentation  [federal_save_act_challenger_model]
(defthm aud-c-challenger-scenario-no-presentation
  (not (aud-c-presents-documentary-proofp 'citizen-a 'registration-attempt-a))
  :rule-classes nil)
;; axiom challenger-scenario-no-fault  [federal_save_act_challenger_model]
(defthm aud-c-challenger-scenario-no-fault
  (aud-c-lacks-qualifying-documents-through-no-faultp 'citizen-a)
  :rule-classes nil)
;; axiom challenger-scenario-material-burden  [federal_save_act_challenger_model]
(defthm aud-c-challenger-scenario-material-burden
  (aud-c-cannot-obtain-qualifying-documents-without-material-burdenp 'citizen-a)
  :rule-classes nil)
;; axiom challenger-scenario-alternative-process-denied  [federal_save_act_challenger_model]
(defthm aud-c-challenger-scenario-alternative-process-denied
  (not (aud-c-alternative-process-approvedp 'citizen-a 'registration-attempt-a))
  :rule-classes nil)
;; axiom challenger-bridge-removal-invalid  [federal_save_act_challenger_model]
(defthm aud-c-challenger-bridge-removal-invalid
  (implies (aud-c-challenger-removal-due-process-violationp 'federal-save-act p) (not (aud-c-valid-regulationp 'federal-save-act p)))
  :rule-classes nil)
;; axiom challenger-bridge-voting-invalid  [federal_save_act_challenger_model]
(defthm aud-c-challenger-bridge-voting-invalid
  (implies (and (aud-c-challenger-voting-burden-establishedp 'federal-save-act p) (aud-c-ballotp b) (aud-c-votes-in-personp p b)) (not (aud-c-valid-regulationp 'federal-save-act b)))
  :rule-classes nil)
;; axiom challenger-scenario-c-material-burden  [federal_save_act_challenger_model]
(defthm aud-c-challenger-scenario-c-material-burden
  (aud-c-cannot-obtain-valid-photo-id-without-material-burdenp 'citizen-c)
  :rule-classes nil)

;;; =========================================================================
;;; WORLD G: the government theory
;;; books: federal_save_act_core, federal_save_act_text_rules, federal_save_act_voting_text_rules, federal_save_act_facts, federal_save_act_scenario, federal_save_act_hinge_common, federal_save_act_hinge_mandatory, federal_save_act_government_model
;;; =========================================================================

;; --- 65 stub / signature definitions ---
(defun aud-g-personp (p) (if (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) t nil))
(defun aud-g-lawp (law) (if (equal law 'federal-save-act) t nil))
(defun aud-g-citizen-of-usp (p) (if (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) t nil))
(defun aud-g-eligible-voterp (p) (if (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) t nil))
(defun aud-g-voter-registration-applicationp (x) (if (equal x 'registration-attempt-a) t nil))
(defun aud-g-has-documentary-proofp (x) (declare (ignore x)) nil)
(defun aud-g-presents-documentary-proofp (p x) (declare (ignore p x)) nil)
(defun aud-g-has-real-id-indicating-citizenshipp (x) (declare (ignore x)) nil)
(defun aud-g-has-valid-us-passportp (x) (declare (ignore x)) nil)
(defun aud-g-has-military-id-with-us-birthp (x) (declare (ignore x)) nil)
(defun aud-g-has-govt-photo-id-showing-us-birthp (x) (declare (ignore x)) nil)
(defun aud-g-has-govt-photo-idp (x) (declare (ignore x)) nil)
(defun aud-g-has-certified-birth-certificatep (x) (declare (ignore x)) nil)
(defun aud-g-has-hospital-birth-recordp (x) (declare (ignore x)) nil)
(defun aud-g-has-final-adoption-decreep (x) (declare (ignore x)) nil)
(defun aud-g-has-consular-report-of-birth-abroadp (x) (declare (ignore x)) nil)
(defun aud-g-has-naturalization-certificatep (x) (declare (ignore x)) nil)
(defun aud-g-has-american-indian-card-kicp (x) (declare (ignore x)) nil)
(defun aud-g-protected-right-to-votep (cs p) (if (and (equal cs 'amend-v-equal-protection) (member-equal p '(citizen-a citizen-b citizen-c citizen-d))) t nil))
(defun aud-g-undue-burden-on-right-to-votep (law p) (declare (ignore law p)) (if t t nil))
(defun aud-g-valid-regulationp (law x) (declare (ignore law x)) (if t t nil))
(defun aud-g-statute-denies-registrationp (law p x) (if (and (equal law 'federal-save-act) (member-equal p '(citizen-a citizen-b citizen-c citizen-d)) (equal x 'registration-attempt-a) (equal p 'citizen-a)) t nil))
(defun aud-g-attempts-to-registerp (p x) (if (and (equal p 'citizen-a) (equal x 'registration-attempt-a)) t nil))
(defun aud-g-registers-by-mailp (p x) (declare (ignore p x)) nil)
(defun aud-g-registers-at-dmvp (p x) (declare (ignore p x)) nil)
(defun aud-g-alternative-process-availablep (p x) (declare (ignore p x)) (if t t nil))
(defun aud-g-alternative-process-approvedp (p x) (declare (ignore p x)) (if t t nil))
(defun aud-g-signs-attestation-under-perjuryp (p) (declare (ignore p)) (if t t nil))
(defun aud-g-submits-other-evidencep (p) (declare (ignore p)) (if t t nil))
(defun aud-g-official-determines-citizenshipp (p) (declare (ignore p)) (if t t nil))
(defun aud-g-registered-voterp (p) (if (member-equal p '(citizen-b citizen-c citizen-d)) t nil))
(defun aud-g-verified-noncitizen-informationp (p) (if (equal p 'citizen-b) t nil))
(defun aud-g-adequate-notice-before-removalp (p) (declare (ignore p)) nil)
(defun aud-g-opportunity-to-be-heardp (p) (declare (ignore p)) nil)
(defun aud-g-statute-removes-registrantp (law p) (if (and (equal law 'federal-save-act) (member-equal p '(citizen-b citizen-c citizen-d)) (equal p 'citizen-b)) t nil))
(defun aud-g-removal-procedure-evenhandedp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-criminal-penalty-for-official-assistancep (official) (declare (ignore official)) nil)
(defun aud-g-criminal-penalty-for-registering-without-proofp (official p) (declare (ignore official p)) nil)
(defun aud-g-document-acquisition-costp (p) (declare (ignore p)) (if t t nil))
(defun aud-g-cost-functions-as-poll-taxp (law p) (declare (ignore law p)) (if t t nil))
(defun aud-g-lacks-qualifying-documents-through-no-faultp (p) (declare (ignore p)) nil)
(defun aud-g-cannot-obtain-qualifying-documents-without-material-burdenp (p) (declare (ignore p)) nil)
(defun aud-g-alternative-process-discretionary-forp (p x) (declare (ignore p x)) nil)
(defun aud-g-substantial-risk-of-erroneous-denialp (law p) (declare (ignore law p)) nil)
(defun aud-g-severe-burden-on-plaintiffp (law p) (declare (ignore law p)) nil)
(defun aud-g-important-government-interestp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-election-integrity-interestp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-registration-procedure-evenhandedp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-documentary-proof-requirement-rationally-connectedp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-reasonable-registration-requirementp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-adequate-alternative-processp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-burden-not-severep (law p) (declare (ignore law p)) (if t t nil))
(defun aud-g-ballotp (b) (if (member-equal b '(ballot-c ballot-d)) t nil))
(defun aud-g-votes-in-personp (p b) (if (or (and (equal p 'citizen-c) (equal b 'ballot-c)) (and (equal p 'citizen-d) (equal b 'ballot-d))) t nil))
(defun aud-g-presents-valid-photo-idp (p b) (declare (ignore p b)) nil)
(defun aud-g-cures-within-deadlinep (p b) (if (and (equal p 'citizen-d) (equal b 'ballot-d)) t nil))
(defun aud-g-statute-denies-regular-ballotp (law p b) (if (and (equal law 'federal-save-act) (member-equal p '(citizen-b citizen-c citizen-d)) (member-equal b '(ballot-c ballot-d))) t nil))
(defun aud-g-cannot-obtain-valid-photo-id-without-material-burdenp (p) (declare (ignore p)) nil)
(defun aud-g-photo-id-requirement-evenhandedp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-provisional-cure-adequatep (law) (declare (ignore law)) (if t t nil))
(defun aud-g-attestation-evidence-satisfies-standardsp (p x) (declare (ignore p x)) (if t t nil))
(defun aud-g-official-discretionary-denialp (p x) (declare (ignore p x)) (if nil t nil))
(defun aud-g-government-defense-establishedp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-government-removal-defense-establishedp (law p) (declare (ignore law p)) (if t t nil))
(defun aud-g-government-voting-defense-establishedp (law) (declare (ignore law)) (if t t nil))

;; --- 12 core definitions over the world ---
(defun aud-g-has-supporting-documentp (x)
  (or (aud-g-has-certified-birth-certificatep x) (aud-g-has-hospital-birth-recordp x) (aud-g-has-final-adoption-decreep x) (aud-g-has-consular-report-of-birth-abroadp x) (aud-g-has-naturalization-certificatep x) (aud-g-has-american-indian-card-kicp x)))
(defun aud-g-has-govt-photo-id-with-supporting-docp (x)
  (and (aud-g-has-govt-photo-idp x) (aud-g-has-supporting-documentp x)))
(defun aud-g-has-any-qualifying-documentp (p)
  (or (aud-g-has-real-id-indicating-citizenshipp p) (aud-g-has-valid-us-passportp p) (aud-g-has-military-id-with-us-birthp p) (aud-g-has-govt-photo-id-showing-us-birthp p) (aud-g-has-govt-photo-id-with-supporting-docp p)))
(defun aud-g-qualified-federal-voterp (p)
  (and (aud-g-personp p) (aud-g-citizen-of-usp p) (aud-g-eligible-voterp p)))
(defun aud-g-registration-transactionp (p x)
  (and (aud-g-personp p) (aud-g-voter-registration-applicationp x) (aud-g-attempts-to-registerp p x)))
(defun aud-g-save-act-denial-triggerp (p x)
  (and (aud-g-registration-transactionp p x) (not (aud-g-presents-documentary-proofp p x)) (not (aud-g-alternative-process-approvedp p x))))
(defun aud-g-constitutional-conflict-conditionp (law constitution-section p x)
  (and (aud-g-lawp law) (aud-g-qualified-federal-voterp p) (aud-g-protected-right-to-votep constitution-section p) (aud-g-registration-transactionp p x) (aud-g-statute-denies-registrationp law p x) (not (aud-g-valid-regulationp law x))))
(defun aud-g-removal-transactionp (p)
  (and (aud-g-personp p) (aud-g-registered-voterp p)))
(defun aud-g-constitutional-removal-conflict-conditionp (law constitution-section p)
  (and (aud-g-lawp law) (aud-g-qualified-federal-voterp p) (aud-g-protected-right-to-votep constitution-section p) (aud-g-removal-transactionp p) (aud-g-statute-removes-registrantp law p) (not (aud-g-valid-regulationp law p))))
(defun aud-g-voting-transactionp (p b)
  (and (aud-g-personp p) (aud-g-registered-voterp p) (aud-g-ballotp b) (aud-g-votes-in-personp p b)))
(defun aud-g-ballot-not-countedp (law p b)
  (and (aud-g-statute-denies-regular-ballotp law p b) (not (aud-g-cures-within-deadlinep p b))))
(defun aud-g-constitutional-voting-conflict-conditionp (law constitution-section p b)
  (and (aud-g-lawp law) (aud-g-qualified-federal-voterp p) (aud-g-protected-right-to-votep constitution-section p) (aud-g-voting-transactionp p b) (aud-g-ballot-not-countedp law p b) (not (aud-g-valid-regulationp law b))))

;; --- 55 audited propositions (5 encapsulate constraints, 50 defaxioms) ---
;; constraint hinge-evidence-type  [federal_save_act_hinge_common]
(defthm aud-g-hinge-evidence-type
  (booleanp (aud-g-attestation-evidence-satisfies-standardsp p x))
  :rule-classes nil)
;; constraint hinge-denial-type  [federal_save_act_hinge_common]
(defthm aud-g-hinge-denial-type
  (booleanp (aud-g-official-discretionary-denialp p x))
  :rule-classes nil)
;; constraint government-valid-regulation-rule  [federal_save_act_government_model]
(defthm aud-g-government-valid-regulation-rule
  (implies (and (aud-g-important-government-interestp law) (aud-g-election-integrity-interestp law) (aud-g-reasonable-registration-requirementp law) (aud-g-registration-procedure-evenhandedp law) (aud-g-documentary-proof-requirement-rationally-connectedp law) (aud-g-adequate-alternative-processp law)) (aud-g-government-defense-establishedp law))
  :rule-classes nil)
;; constraint government-removal-defense-rule  [federal_save_act_government_model]
(defthm aud-g-government-removal-defense-rule
  (implies (and (aud-g-verified-noncitizen-informationp p) (aud-g-important-government-interestp law) (aud-g-removal-procedure-evenhandedp law)) (aud-g-government-removal-defense-establishedp law p))
  :rule-classes nil)
;; constraint government-voting-defense-rule  [federal_save_act_government_model]
(defthm aud-g-government-voting-defense-rule
  (implies (and (aud-g-important-government-interestp law) (aud-g-photo-id-requirement-evenhandedp law) (aud-g-provisional-cure-adequatep law)) (aud-g-government-voting-defense-establishedp law))
  :rule-classes nil)
;; axiom text-save-act-documentary-proof-requirement  [federal_save_act_text_rules]
(defthm aud-g-text-save-act-documentary-proof-requirement
  (implies (and (aud-g-personp p) (aud-g-voter-registration-applicationp x) (aud-g-attempts-to-registerp p x) (not (aud-g-presents-documentary-proofp p x)) (not (aud-g-alternative-process-approvedp p x))) (aud-g-statute-denies-registrationp 'federal-save-act p x))
  :rule-classes nil)
;; axiom text-save-act-removal-upon-verified-information  [federal_save_act_text_rules]
(defthm aud-g-text-save-act-removal-upon-verified-information
  (implies (and (aud-g-personp p) (aud-g-registered-voterp p) (aud-g-verified-noncitizen-informationp p)) (aud-g-statute-removes-registrantp 'federal-save-act p))
  :rule-classes nil)
;; axiom text-photo-id-required-for-regular-ballot  [federal_save_act_voting_text_rules]
(defthm aud-g-text-photo-id-required-for-regular-ballot
  (implies (and (aud-g-personp p) (aud-g-registered-voterp p) (aud-g-ballotp b) (aud-g-votes-in-personp p b) (not (aud-g-presents-valid-photo-idp p b))) (aud-g-statute-denies-regular-ballotp 'federal-save-act p b))
  :rule-classes nil)
;; axiom text-save-act-is-law  [federal_save_act_facts]
(defthm aud-g-text-save-act-is-law
  (aud-g-lawp 'federal-save-act)
  :rule-classes nil)
;; axiom text-documentary-proof-from-qualifying-documents  [federal_save_act_facts]
(defthm aud-g-text-documentary-proof-from-qualifying-documents
  (implies (aud-g-has-any-qualifying-documentp p) (aud-g-has-documentary-proofp p))
  :rule-classes nil)
;; axiom scenario-person  [federal_save_act_scenario]
(defthm aud-g-scenario-person
  (aud-g-personp 'citizen-a)
  :rule-classes nil)
;; axiom scenario-citizen  [federal_save_act_scenario]
(defthm aud-g-scenario-citizen
  (aud-g-citizen-of-usp 'citizen-a)
  :rule-classes nil)
;; axiom scenario-eligible  [federal_save_act_scenario]
(defthm aud-g-scenario-eligible
  (aud-g-eligible-voterp 'citizen-a)
  :rule-classes nil)
;; axiom scenario-application  [federal_save_act_scenario]
(defthm aud-g-scenario-application
  (aud-g-voter-registration-applicationp 'registration-attempt-a)
  :rule-classes nil)
;; axiom scenario-attempts-to-register  [federal_save_act_scenario]
(defthm aud-g-scenario-attempts-to-register
  (aud-g-attempts-to-registerp 'citizen-a 'registration-attempt-a)
  :rule-classes nil)
;; axiom scenario-no-documentary-proof  [federal_save_act_scenario]
(defthm aud-g-scenario-no-documentary-proof
  (not (aud-g-has-documentary-proofp 'citizen-a))
  :rule-classes nil)
;; axiom scenario-b-person  [federal_save_act_scenario]
(defthm aud-g-scenario-b-person
  (aud-g-personp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-citizen  [federal_save_act_scenario]
(defthm aud-g-scenario-b-citizen
  (aud-g-citizen-of-usp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-eligible  [federal_save_act_scenario]
(defthm aud-g-scenario-b-eligible
  (aud-g-eligible-voterp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-registered  [federal_save_act_scenario]
(defthm aud-g-scenario-b-registered
  (aud-g-registered-voterp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-verified-noncitizen-information  [federal_save_act_scenario]
(defthm aud-g-scenario-b-verified-noncitizen-information
  (aud-g-verified-noncitizen-informationp 'citizen-b)
  :rule-classes nil)
;; axiom scenario-b-no-notice  [federal_save_act_scenario]
(defthm aud-g-scenario-b-no-notice
  (not (aud-g-adequate-notice-before-removalp 'citizen-b))
  :rule-classes nil)
;; axiom scenario-b-no-hearing  [federal_save_act_scenario]
(defthm aud-g-scenario-b-no-hearing
  (not (aud-g-opportunity-to-be-heardp 'citizen-b))
  :rule-classes nil)
;; axiom scenario-c-person  [federal_save_act_scenario]
(defthm aud-g-scenario-c-person
  (aud-g-personp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-citizen  [federal_save_act_scenario]
(defthm aud-g-scenario-c-citizen
  (aud-g-citizen-of-usp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-eligible  [federal_save_act_scenario]
(defthm aud-g-scenario-c-eligible
  (aud-g-eligible-voterp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-registered  [federal_save_act_scenario]
(defthm aud-g-scenario-c-registered
  (aud-g-registered-voterp 'citizen-c)
  :rule-classes nil)
;; axiom scenario-c-ballot  [federal_save_act_scenario]
(defthm aud-g-scenario-c-ballot
  (aud-g-ballotp 'ballot-c)
  :rule-classes nil)
;; axiom scenario-c-votes-in-person  [federal_save_act_scenario]
(defthm aud-g-scenario-c-votes-in-person
  (aud-g-votes-in-personp 'citizen-c 'ballot-c)
  :rule-classes nil)
;; axiom scenario-c-no-valid-photo-id  [federal_save_act_scenario]
(defthm aud-g-scenario-c-no-valid-photo-id
  (not (aud-g-presents-valid-photo-idp 'citizen-c 'ballot-c))
  :rule-classes nil)
;; axiom scenario-c-no-cure  [federal_save_act_scenario]
(defthm aud-g-scenario-c-no-cure
  (not (aud-g-cures-within-deadlinep 'citizen-c 'ballot-c))
  :rule-classes nil)
;; axiom scenario-d-person  [federal_save_act_scenario]
(defthm aud-g-scenario-d-person
  (aud-g-personp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-citizen  [federal_save_act_scenario]
(defthm aud-g-scenario-d-citizen
  (aud-g-citizen-of-usp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-eligible  [federal_save_act_scenario]
(defthm aud-g-scenario-d-eligible
  (aud-g-eligible-voterp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-registered  [federal_save_act_scenario]
(defthm aud-g-scenario-d-registered
  (aud-g-registered-voterp 'citizen-d)
  :rule-classes nil)
;; axiom scenario-d-ballot  [federal_save_act_scenario]
(defthm aud-g-scenario-d-ballot
  (aud-g-ballotp 'ballot-d)
  :rule-classes nil)
;; axiom scenario-d-votes-in-person  [federal_save_act_scenario]
(defthm aud-g-scenario-d-votes-in-person
  (aud-g-votes-in-personp 'citizen-d 'ballot-d)
  :rule-classes nil)
;; axiom scenario-d-no-valid-photo-id  [federal_save_act_scenario]
(defthm aud-g-scenario-d-no-valid-photo-id
  (not (aud-g-presents-valid-photo-idp 'citizen-d 'ballot-d))
  :rule-classes nil)
;; axiom scenario-d-cures  [federal_save_act_scenario]
(defthm aud-g-scenario-d-cures
  (aud-g-cures-within-deadlinep 'citizen-d 'ballot-d)
  :rule-classes nil)
;; axiom semantic-a-mandatory-approval  [federal_save_act_hinge_mandatory]
(defthm aud-g-semantic-a-mandatory-approval
  (implies (and (aud-g-signs-attestation-under-perjuryp p) (aud-g-submits-other-evidencep p) (aud-g-attestation-evidence-satisfies-standardsp p x)) (aud-g-alternative-process-approvedp p x))
  :rule-classes nil)
;; axiom government-bridge-defense-validates  [federal_save_act_government_model]
(defthm aud-g-government-bridge-defense-validates
  (implies (and (aud-g-government-defense-establishedp law) (aud-g-voter-registration-applicationp x)) (aud-g-valid-regulationp law x))
  :rule-classes nil)
;; axiom government-election-integrity-interest  [federal_save_act_government_model]
(defthm aud-g-government-election-integrity-interest
  (aud-g-election-integrity-interestp 'federal-save-act)
  :rule-classes nil)
;; axiom government-important-interest  [federal_save_act_government_model]
(defthm aud-g-government-important-interest
  (aud-g-important-government-interestp 'federal-save-act)
  :rule-classes nil)
;; axiom government-reasonable-requirement  [federal_save_act_government_model]
(defthm aud-g-government-reasonable-requirement
  (aud-g-reasonable-registration-requirementp 'federal-save-act)
  :rule-classes nil)
;; axiom government-procedure-evenhanded  [federal_save_act_government_model]
(defthm aud-g-government-procedure-evenhanded
  (aud-g-registration-procedure-evenhandedp 'federal-save-act)
  :rule-classes nil)
;; axiom government-rationally-connected  [federal_save_act_government_model]
(defthm aud-g-government-rationally-connected
  (aud-g-documentary-proof-requirement-rationally-connectedp 'federal-save-act)
  :rule-classes nil)
;; axiom government-adequate-alternative  [federal_save_act_government_model]
(defthm aud-g-government-adequate-alternative
  (aud-g-adequate-alternative-processp 'federal-save-act)
  :rule-classes nil)
;; axiom government-burden-not-severe  [federal_save_act_government_model]
(defthm aud-g-government-burden-not-severe
  (aud-g-burden-not-severep 'federal-save-act p)
  :rule-classes nil)
;; axiom government-assume-right-to-vote-arguendo  [federal_save_act_government_model]
(defthm aud-g-government-assume-right-to-vote-arguendo
  (aud-g-protected-right-to-votep 'amend-v-equal-protection 'citizen-a)
  :rule-classes nil)
;; axiom government-scenario-alternative-process-approved  [federal_save_act_government_model]
(defthm aud-g-government-scenario-alternative-process-approved
  (aud-g-alternative-process-approvedp 'citizen-a 'registration-attempt-a)
  :rule-classes nil)
;; axiom government-bridge-removal-validates  [federal_save_act_government_model]
(defthm aud-g-government-bridge-removal-validates
  (implies (aud-g-government-removal-defense-establishedp law p) (aud-g-valid-regulationp law p))
  :rule-classes nil)
;; axiom government-removal-procedure-evenhanded  [federal_save_act_government_model]
(defthm aud-g-government-removal-procedure-evenhanded
  (aud-g-removal-procedure-evenhandedp 'federal-save-act)
  :rule-classes nil)
;; axiom government-bridge-voting-validates  [federal_save_act_government_model]
(defthm aud-g-government-bridge-voting-validates
  (implies (and (aud-g-government-voting-defense-establishedp law) (aud-g-ballotp b)) (aud-g-valid-regulationp law b))
  :rule-classes nil)
;; axiom government-photo-id-evenhanded  [federal_save_act_government_model]
(defthm aud-g-government-photo-id-evenhanded
  (aud-g-photo-id-requirement-evenhandedp 'federal-save-act)
  :rule-classes nil)
;; axiom government-provisional-cure-adequate  [federal_save_act_government_model]
(defthm aud-g-government-provisional-cure-adequate
  (aud-g-provisional-cure-adequatep 'federal-save-act)
  :rule-classes nil)

;;; =========================================================================
;;; JOINT UNSATISFIABILITY of the two registration bridges (propositional):
;;; the challenger needs (not (valid-regulationp law x)) and the government
;;; needs (valid-regulationp law x) for the same application x.  No world
;;; satisfies both, which is why the party books are never loaded together.
;;; =========================================================================
(defthm parties-registration-bridges-jointly-unsatisfiable
  (not (and (implies ci (not v))   ; challenger-bridge-regulation-invalid
            (implies gd v)         ; government-bridge-defense-validates
            ci gd))
  :rule-classes nil)
