(in-package "ACL2")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; federal_save_act_core.lisp  —  v6.0 (hybrid encapsulate architecture)
;; Neutral legal vocabulary and generic conflict condition.
;; Generated by the Constitutional ACL2 Stress-Test Agent.
;;
;; This book defines uninterpreted predicates (defstub) and neutral
;; helper functions.  It does not contain any facts, interpretations,
;; or assumptions.  All models include this book.
;;
;; v3 changes (retained in v5.2):
;;   • Added presents-documentary-proofp (possession ≠ presentation)
;;   • Completed has-any-qualifying-documentp with birth cert + nat cert
;;   • Added factored intermediate predicates:
;;       qualified-federal-voterp, registration-transactionp,
;;       save-act-denial-triggerp
;;   • Added Mathis burden-severity stubs (neutral — both sides constrain)
;;   • Refactored constitutional-conflict-conditionp through intermediates
;;
;; Domain: Federal voter registration / documentary proof of citizenship
;; Constitutional provisions: Elections Clause (Art. I, §4),
;;   Equal Protection (Amend. XIV, §1 via Amend. V), Poll Tax (Amend. XXIV)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; =========================================================================
;;; Ontological predicates
;;; =========================================================================

(defstub personp (x) t)                        ; x is a person
(defstub lawp (x) t)                           ; x is a law/statute
(defstub citizen-of-usp (x) t)                 ; x is a citizen of the United States
(defstub eligible-voterp (x) t)                ; x is eligible to vote in federal elections
(defstub voter-registration-applicationp (x) t) ; x is a voter reg application

;;; =========================================================================
;;; Documentary proof predicates (NVRA § 3(b) as amended)
;;;
;;; v3 distinguishes POSSESSION from PRESENTATION:
;;;   has-documentary-proofp    — person possesses qualifying documents
;;;   presents-documentary-proofp — person presents documents WITH the
;;;                                  application (the statute's actual
;;;                                  requirement: "presents ... with the
;;;                                  application")
;;; =========================================================================

(defstub has-documentary-proofp (x) t)         ; x possesses documentary proof
(defstub presents-documentary-proofp (p x) t)  ; p presents proof with application x

;; Individual document-type predicates
(defstub has-real-id-indicating-citizenshipp (x) t)
(defstub has-valid-us-passportp (x) t)
(defstub has-military-id-with-us-birthp (x) t)
(defstub has-govt-photo-id-showing-us-birthp (x) t)
(defstub has-govt-photo-idp (x) t)              ; § 3(b)(5) anchor photo ID
;; § 3(b)(5)(A)-(F) supporting documents — proof ONLY with an anchor photo ID
(defstub has-certified-birth-certificatep (x) t)
(defstub has-hospital-birth-recordp (x) t)
(defstub has-final-adoption-decreep (x) t)
(defstub has-consular-report-of-birth-abroadp (x) t)
(defstub has-naturalization-certificatep (x) t)
(defstub has-american-indian-card-kicp (x) t)

;; v6.0: was a bare defstub; now DEFINED from the statute's structure.
;; § 3(b)(5): "a valid government-issued photo identification card ...
;; but only if presented together with one or more of the following".
(defun has-supporting-documentp (x)
  (or (has-certified-birth-certificatep x)
      (has-hospital-birth-recordp x)
      (has-final-adoption-decreep x)
      (has-consular-report-of-birth-abroadp x)
      (has-naturalization-certificatep x)
      (has-american-indian-card-kicp x)))

(defun has-govt-photo-id-with-supporting-docp (x)
  (and (has-govt-photo-idp x)
       (has-supporting-documentp x)))

;;; =========================================================================
;;; Constitutional predicates
;;; =========================================================================

(defstub protected-right-to-votep (constitution-section x) t)
  ;; x has a constitutionally protected right to vote under constitution-section

(defstub undue-burden-on-right-to-votep (law x) t)
  ;; law imposes an undue burden on x's right to vote

;;; =========================================================================
;;; Regulatory predicates
;;; =========================================================================

(defstub valid-regulationp (law x) t)
  ;; law is a constitutionally valid regulation of the activity/object x

(defstub statute-denies-registrationp (law p x) t)
  ;; law denies person p registration through application x

;;; =========================================================================
;;; Conduct / transaction verbs
;;; =========================================================================

(defstub attempts-to-registerp (p x) t)        ; p attempts to register via application x
(defstub registers-by-mailp (p x) t)           ; p registers via mail application x
(defstub registers-at-dmvp (p x) t)            ; p registers via motor-voter at DMV

;;; =========================================================================
;;; Alternative process predicates (NVRA § 8(j)(2)(A))
;;; =========================================================================

(defstub alternative-process-availablep (p x) t) ; alternative attestation process is available
(defstub alternative-process-approvedp (p x) t)  ; p approved via alternative process for app x
(defstub signs-attestation-under-perjuryp (p) t) ; p signs attestation under penalty of perjury
(defstub submits-other-evidencep (p) t)           ; p submits other evidence of citizenship
(defstub official-determines-citizenshipp (p) t)  ; official determines p is a citizen

;;; =========================================================================
;;; Removal predicates (NVRA § 8(k))
;;; =========================================================================

(defstub registered-voterp (p) t)                 ; p is on the official list of eligible voters
(defstub verified-noncitizen-informationp (p) t) ; State holds documentation/verified info that p is not a citizen
(defstub adequate-notice-before-removalp (p) t)  ; p received adequate notice before removal
(defstub opportunity-to-be-heardp (p) t)          ; p had opportunity to contest removal
(defstub statute-removes-registrantp (law p) t)  ; law removes registrant p from the rolls
(defstub removal-procedure-evenhandedp (law) t)  ; (government-side) removal procedure is evenhanded

;;; =========================================================================
;;; Penalty predicates
;;; =========================================================================

(defstub criminal-penalty-for-official-assistancep (official) t)
(defstub criminal-penalty-for-registering-without-proofp (official p) t)

;;; =========================================================================
;;; Cost predicates (for poll-tax analysis)
;;; =========================================================================

(defstub document-acquisition-costp (p) t)     ; p must pay to obtain qualifying documents
(defstub cost-functions-as-poll-taxp (law p) t) ; the cost functions as a de facto poll tax
(defstub fee-waiver-availablep (law) t)         ; law (or the State under it) provides the documents free

;;; =========================================================================
;;; Mathis / Anderson-Burdick burden-severity predicates
;;;
;;; These are NEUTRAL stubs.  Both the challenger and government models
;;; constrain them differently.  Placing them here lets the core and the
;;; generalized theorems reference them without importing interpretive
;;; content.
;;;
;;; Challenger-side (turned ON in challenger model):
;;;   substantial-risk-of-erroneous-denialp
;;;   severe-burden-on-plaintiffp
;;;   cannot-obtain-qualifying-documents-without-material-burdenp
;;;   alternative-process-discretionary-forp
;;;
;;; Government-side (turned ON in government model):
;;;   important-government-interestp
;;;   registration-procedure-evenhandedp
;;;   documentary-proof-requirement-rationally-connectedp
;;;   adequate-alternative-processp  (also used as neutral pred)
;;;   burden-not-severep
;;; =========================================================================

;; Challenger-side burden predicates
(defstub lacks-qualifying-documents-through-no-faultp (p) t)
(defstub cannot-obtain-qualifying-documents-without-material-burdenp (p) t)
(defstub alternative-process-discretionary-forp (p x) t)
(defstub substantial-risk-of-erroneous-denialp (law p) t)
(defstub severe-burden-on-plaintiffp (law p) t)

;; Government-side defense predicates
(defstub important-government-interestp (law) t)
(defstub election-integrity-interestp (law) t)
(defstub registration-procedure-evenhandedp (law) t)
(defstub documentary-proof-requirement-rationally-connectedp (law) t)
(defstub reasonable-registration-requirementp (law) t)
(defstub adequate-alternative-processp (law) t)
(defstub burden-not-severep (law p) t)

;;; =========================================================================
;;; Neutral helper functions
;;; =========================================================================

;; BRIDGE_RULE: A person has documentary proof if they possess any
;; qualifying document from the statutory list.
;; This is a neutral structural rule derived from NVRA § 3(b).
;;
;; v6.0 FIX: v3 added birth certificates and naturalization certificates
;; as STANDALONE disjuncts.  Under § 3(b)(5) they are supporting documents
;; that count only together with a government photo ID; that pairing is
;; already has-govt-photo-id-with-supporting-docp.  The standalone
;; disjuncts are removed.  (Mirrors the generated documentary-proof-bundlep
;; over document lists in federal_save_act_document_rules.lisp.)
(defun has-any-qualifying-documentp (p)
  (or (has-real-id-indicating-citizenshipp p)
      (has-valid-us-passportp p)
      (has-military-id-with-us-birthp p)
      (has-govt-photo-id-showing-us-birthp p)
      (has-govt-photo-id-with-supporting-docp p)))

;;; =========================================================================
;;; Factored intermediate predicates (v3)
;;;
;;; Instead of one big final theorem relying on many axioms, v3
;;; introduces smaller intermediate propositions for ACL2 to reason
;;; over.  These are NEUTRAL structural compositions.
;;; =========================================================================

;; A person is a qualified federal voter if they are a person, a citizen,
;; and eligible.
(defun qualified-federal-voterp (p)
  (and (personp p)
       (citizen-of-usp p)
       (eligible-voterp p)))

;; A registration transaction occurs when a person attempts to register
;; via a voter registration application.
(defun registration-transactionp (p x)
  (and (personp p)
       (voter-registration-applicationp x)
       (attempts-to-registerp p x)))

;; The SAVE Act denial trigger fires when a person does not present
;; documentary proof with their application AND is not approved through
;; the alternative process.
;;
;; NOTE: This uses presents-documentary-proofp (not has-documentary-proofp)
;; because the statute requires presentation with the application, not
;; mere possession.
(defun save-act-denial-triggerp (p x)
  (and (registration-transactionp p x)
       (not (presents-documentary-proofp p x))
       (not (alternative-process-approvedp p x))))

;;; =========================================================================
;;; Generic constitutional conflict condition (v3 — factored)
;;;
;;; Pattern (composed from intermediate predicates):
;;;   1. The law is a law
;;;   2. The person is a qualified federal voter
;;;   3. The person has a constitutionally protected right to vote
;;;   4. The person attempts to register (registration transaction)
;;;   5. The statute denies that person's registration
;;;   6. The statute is NOT a valid regulation
;;; =========================================================================

(defun constitutional-conflict-conditionp (law constitution-section p x)
  (and (lawp law)
       (qualified-federal-voterp p)
       (protected-right-to-votep constitution-section p)
       (registration-transactionp p x)
       (statute-denies-registrationp law p x)
       (not (valid-regulationp law x))))

;;; =========================================================================
;;; Election-day predicates (SAVE America Act § 3 / HAVA § 303A) — v6.5
;;; =========================================================================

(defstub ballotp (b) t)                          ; b is a ballot in a federal election
(defstub votes-in-personp (p b) t)               ; p seeks to vote in person with ballot b
(defstub presents-valid-photo-idp (p b) t)       ; p presents valid physical photo ID for b
(defstub cures-within-deadlinep (p b) t)         ; p cures a provisional ballot within 3 days
(defstub statute-denies-regular-ballotp (law p b) t) ; law forbids providing regular ballot b to p
(defstub cannot-obtain-valid-photo-id-without-material-burdenp (p) t) ; challenger-side empirical
(defstub photo-id-requirement-evenhandedp (law) t)   ; government-side
(defstub provisional-cure-adequatep (law) t)         ; government-side

;;; =========================================================================
;;; Removal-side conflict condition (v6.1)
;;;
;;; § 8(k) acts on a REGISTRANT, not on an application, so removal gets its
;;; own conflict condition with the same shape as the registration one.
;;; The object of valid-regulationp is the registrant p: "the removal rule
;;; is a valid regulation as applied to p".  (The registration condition
;;; uses the application x.)  Party models constrain valid-regulationp for
;;; applications and for registrants SEPARATELY — see the v6.1 narrowing of
;;; the bridge rules in the challenger and government books.
;;; =========================================================================

(defun removal-transactionp (p)
  (and (personp p)
       (registered-voterp p)))

(defun constitutional-removal-conflict-conditionp (law constitution-section p)
  (and (lawp law)
       (qualified-federal-voterp p)
       (protected-right-to-votep constitution-section p)
       (removal-transactionp p)
       (statute-removes-registrantp law p)
       (not (valid-regulationp law p))))

;;; =========================================================================
;;; Voting-side conflict condition (v6.5)
;;;
;;; § 303A acts on a BALLOT.  The statute never denies the vote outright:
;;; a voter without ID gets a provisional ballot, counted if cured within
;;; 3 days.  So the condition requires BOTH the regular-ballot denial AND
;;; failure to cure — only then has the citizen's ballot gone uncounted.
;;; The object of valid-regulationp is the ballot b.
;;; =========================================================================

(defun voting-transactionp (p b)
  (and (personp p)
       (registered-voterp p)
       (ballotp b)
       (votes-in-personp p b)))

(defun ballot-not-countedp (law p b)
  (and (statute-denies-regular-ballotp law p b)
       (not (cures-within-deadlinep p b))))

(defun constitutional-voting-conflict-conditionp (law constitution-section p b)
  (and (lawp law)
       (qualified-federal-voterp p)
       (protected-right-to-votep constitution-section p)
       (voting-transactionp p b)
       (ballot-not-countedp law p b)
       (not (valid-regulationp law b))))

;;; =========================================================================
;;; Shared structural lemmas about the conflict condition (v6.0)
;;;
;;; v5 restated the two facts below in five different books
;;; (consistency_check, model_consistency, independence, doctrine_proofs,
;;; government_model).  They depend on nothing but the definitions above,
;;; so they belong here, once, where every model inherits them.
;;; =========================================================================

;; A valid regulation defeats the conflict condition outright.
(defthm core-valid-regulation-defeats-conflict
  (implies (valid-regulationp law x)
           (not (constitutional-conflict-conditionp law cs p x))))

;; Given every other precondition, the conflict condition is exactly
;; (not (valid-regulationp law x)) — the single structural pivot.
(defthm core-conflict-pivots-on-valid-regulation
  (implies (and (lawp law)
                (qualified-federal-voterp p)
                (protected-right-to-votep cs p)
                (registration-transactionp p x)
                (statute-denies-registrationp law p x))
           (iff (constitutional-conflict-conditionp law cs p x)
                (not (valid-regulationp law x)))))

;; Removal-side twins of the two lemmas above.
(defthm core-valid-regulation-defeats-removal-conflict
  (implies (valid-regulationp law p)
           (not (constitutional-removal-conflict-conditionp law cs p))))

(defthm core-removal-conflict-pivots-on-valid-regulation
  (implies (and (lawp law)
                (qualified-federal-voterp p)
                (protected-right-to-votep cs p)
                (removal-transactionp p)
                (statute-removes-registrantp law p))
           (iff (constitutional-removal-conflict-conditionp law cs p)
                (not (valid-regulationp law p)))))

;; Voting-side twins.
(defthm core-valid-regulation-defeats-voting-conflict
  (implies (valid-regulationp law b)
           (not (constitutional-voting-conflict-conditionp law cs p b))))

(defthm core-voting-conflict-pivots-on-valid-regulation
  (implies (and (lawp law)
                (qualified-federal-voterp p)
                (protected-right-to-votep cs p)
                (voting-transactionp p b)
                (ballot-not-countedp law p b))
           (iff (constitutional-voting-conflict-conditionp law cs p b)
                (not (valid-regulationp law b)))))

;; A cured provisional ballot is never a conflict: the vote was counted.
(defthm core-cure-defeats-voting-conflict
  (implies (cures-within-deadlinep p b)
           (not (constitutional-voting-conflict-conditionp law cs p b))))
