(in-package "ACL2")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; mega_act_s113_consistency_audit.lisp  —  GENERATED by tools/gen_consistency_audit.py
;;
;; CONSISTENCY AUDIT of each party's trusted base (cf. Vero, arXiv:2608.13522 § 3.5).
;; For each party theory, every defstub gets a concrete toy-world definition
;; (aud-<party>-<name>), every core defun is re-defined over that world, and
;; every defaxiom / encapsulate constraint of the theory is restated over the
;; world and PROVED.  Certification of this book = the theory is satisfiable.
;; A failing theorem names an inconsistent axiom or a missing condition.
;; This book includes no party book and contains no defaxiom (neutral).
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; =========================================================================
;;; WORLD C: the challenger theory
;;; books: mega_act_s113_core, mega_act_s113_text_rules, mega_act_s113_scenario, mega_act_s113_hinge_common, mega_act_s113_hinge_data, mega_act_s113_challenger_model
;;; =========================================================================

;; --- 20 stub / signature definitions ---
(defun aud-c-personp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-c-lawp (law) (if (equal law 'mega-act) t nil))
(defun aud-c-citizen-of-usp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-c-eligible-voterp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-c-registered-voterp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-c-save-indicates-noncitizenp (p) (if (equal p 'registrant-r) t nil))
(defun aud-c-determined-ineligible-noncitizenp (p) (if (equal p 'registrant-r) t nil))
(defun aud-c-statute-removes-registrantp (law p) (if (and (equal law 'mega-act) (equal p 'registrant-r)) t nil))
(defun aud-c-removable-at-any-timep (p) (if (equal p 'registrant-r) t nil))
(defun aud-c-removed-for-residence-changep (p) (declare (ignore p)) (if nil t nil))
(defun aud-c-notice-card-sentp (p) (declare (ignore p)) (if nil t nil))
(defun aud-c-adequate-notice-before-removalp (p) (declare (ignore p)) (if nil t nil))
(defun aud-c-opportunity-to-be-heardp (p) (declare (ignore p)) (if nil t nil))
(defun aud-c-protected-right-to-votep (cs p) (if (and (equal cs 'amend-v-due-process) (member-equal p '(registrant-r))) t nil))
(defun aud-c-valid-regulationp (law x) (declare (ignore law x)) (if nil t nil))
(defun aud-c-important-government-interestp (law) (declare (ignore law)) nil)
(defun aud-c-removal-procedure-evenhandedp (law) (declare (ignore law)) nil)
(defun aud-c-save-data-reliablep (law) (declare (ignore law)) nil)
(defun aud-c-challenger-right-to-vote-establishedp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-c-challenger-removal-due-process-violationp (law p) (if (and (equal law 'mega-act) (equal p 'registrant-r)) t nil))

;; --- 3 core definitions over the world ---
(defun aud-c-qualified-federal-voterp (p)
  (and (aud-c-personp p) (aud-c-citizen-of-usp p) (aud-c-eligible-voterp p)))
(defun aud-c-removal-transactionp (p)
  (and (aud-c-personp p) (aud-c-registered-voterp p)))
(defun aud-c-constitutional-removal-conflict-conditionp (law cs p)
  (and (aud-c-lawp law) (aud-c-qualified-federal-voterp p) (aud-c-protected-right-to-votep cs p) (aud-c-removal-transactionp p) (aud-c-statute-removes-registrantp law p) (not (aud-c-valid-regulationp law p))))

;; --- 16 audited propositions (2 encapsulate constraints, 14 defaxioms) ---
;; constraint challenger-fundamental-right-rule  [mega_act_s113_challenger_model]
(defthm aud-c-challenger-fundamental-right-rule
  (implies (aud-c-qualified-federal-voterp p) (aud-c-challenger-right-to-vote-establishedp p))
  :rule-classes nil)
;; constraint challenger-removal-without-process-is-violation  [mega_act_s113_challenger_model]
(defthm aud-c-challenger-removal-without-process-is-violation
  (implies (and (aud-c-qualified-federal-voterp p) (aud-c-registered-voterp p) (aud-c-statute-removes-registrantp 'mega-act p) (not (aud-c-adequate-notice-before-removalp p)) (not (aud-c-opportunity-to-be-heardp p))) (aud-c-challenger-removal-due-process-violationp 'mega-act p))
  :rule-classes nil)
;; axiom text-s113-noncitizen-determination-removes  [mega_act_s113_text_rules]
(defthm aud-c-text-s113-noncitizen-determination-removes
  (implies (and (aud-c-personp p) (aud-c-registered-voterp p) (aud-c-determined-ineligible-noncitizenp p)) (aud-c-statute-removes-registrantp 'mega-act p))
  :rule-classes nil)
;; axiom text-s113-noncitizen-removal-at-any-time  [mega_act_s113_text_rules]
(defthm aud-c-text-s113-noncitizen-removal-at-any-time
  (implies (and (aud-c-personp p) (aud-c-determined-ineligible-noncitizenp p)) (aud-c-removable-at-any-timep p))
  :rule-classes nil)
;; axiom text-s113-residence-removal-requires-return-card  [mega_act_s113_text_rules]
(defthm aud-c-text-s113-residence-removal-requires-return-card
  (implies (and (aud-c-personp p) (aud-c-registered-voterp p) (aud-c-removed-for-residence-changep p)) (aud-c-notice-card-sentp p))
  :rule-classes nil)
;; axiom scenario-r-person  [mega_act_s113_scenario]
(defthm aud-c-scenario-r-person
  (aud-c-personp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-citizen  [mega_act_s113_scenario]
(defthm aud-c-scenario-r-citizen
  (aud-c-citizen-of-usp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-eligible  [mega_act_s113_scenario]
(defthm aud-c-scenario-r-eligible
  (aud-c-eligible-voterp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-registered  [mega_act_s113_scenario]
(defthm aud-c-scenario-r-registered
  (aud-c-registered-voterp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-save-indicates-noncitizen  [mega_act_s113_scenario]
(defthm aud-c-scenario-r-save-indicates-noncitizen
  (aud-c-save-indicates-noncitizenp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-no-notice  [mega_act_s113_scenario]
(defthm aud-c-scenario-r-no-notice
  (not (aud-c-adequate-notice-before-removalp 'registrant-r))
  :rule-classes nil)
;; axiom scenario-r-no-hearing  [mega_act_s113_scenario]
(defthm aud-c-scenario-r-no-hearing
  (not (aud-c-opportunity-to-be-heardp 'registrant-r))
  :rule-classes nil)
;; axiom text-mega-act-is-law  [mega_act_s113_scenario]
(defthm aud-c-text-mega-act-is-law
  (aud-c-lawp 'mega-act)
  :rule-classes nil)
;; axiom semantic-a-save-data-is-determination  [mega_act_s113_hinge_data]
(defthm aud-c-semantic-a-save-data-is-determination
  (implies (aud-c-save-indicates-noncitizenp p) (aud-c-determined-ineligible-noncitizenp p))
  :rule-classes nil)
;; axiom challenger-bridge-right-to-vote  [mega_act_s113_challenger_model]
(defthm aud-c-challenger-bridge-right-to-vote
  (implies (aud-c-challenger-right-to-vote-establishedp p) (aud-c-protected-right-to-votep 'amend-v-due-process p))
  :rule-classes nil)
;; axiom challenger-bridge-removal-invalid  [mega_act_s113_challenger_model]
(defthm aud-c-challenger-bridge-removal-invalid
  (implies (aud-c-challenger-removal-due-process-violationp 'mega-act p) (not (aud-c-valid-regulationp 'mega-act p)))
  :rule-classes nil)

;;; =========================================================================
;;; WORLD G: the government theory
;;; books: mega_act_s113_core, mega_act_s113_text_rules, mega_act_s113_scenario, mega_act_s113_hinge_common, mega_act_s113_hinge_process, mega_act_s113_government_model
;;; =========================================================================

;; --- 19 stub / signature definitions ---
(defun aud-g-personp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-g-lawp (law) (if (equal law 'mega-act) t nil))
(defun aud-g-citizen-of-usp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-g-eligible-voterp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-g-registered-voterp (p) (if (member-equal p '(registrant-r)) t nil))
(defun aud-g-save-indicates-noncitizenp (p) (if (equal p 'registrant-r) t nil))
(defun aud-g-determined-ineligible-noncitizenp (p) (declare (ignore p)) (if nil t nil))
(defun aud-g-statute-removes-registrantp (law p) (declare (ignore law p)) (if nil t nil))
(defun aud-g-removable-at-any-timep (p) (declare (ignore p)) (if nil t nil))
(defun aud-g-removed-for-residence-changep (p) (declare (ignore p)) (if nil t nil))
(defun aud-g-notice-card-sentp (p) (declare (ignore p)) (if nil t nil))
(defun aud-g-adequate-notice-before-removalp (p) (declare (ignore p)) (if nil t nil))
(defun aud-g-opportunity-to-be-heardp (p) (declare (ignore p)) (if nil t nil))
(defun aud-g-protected-right-to-votep (cs p) (if (and (equal cs 'amend-v-due-process) (member-equal p '(registrant-r))) t nil))
(defun aud-g-valid-regulationp (law x) (declare (ignore law x)) (if t t nil))
(defun aud-g-important-government-interestp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-removal-procedure-evenhandedp (law) (declare (ignore law)) (if t t nil))
(defun aud-g-save-data-reliablep (law) (declare (ignore law)) (if t t nil))
(defun aud-g-government-removal-defense-establishedp (law p) (declare (ignore law)) (if (equal p 'registrant-r) t nil))

;; --- 3 core definitions over the world ---
(defun aud-g-qualified-federal-voterp (p)
  (and (aud-g-personp p) (aud-g-citizen-of-usp p) (aud-g-eligible-voterp p)))
(defun aud-g-removal-transactionp (p)
  (and (aud-g-personp p) (aud-g-registered-voterp p)))
(defun aud-g-constitutional-removal-conflict-conditionp (law cs p)
  (and (aud-g-lawp law) (aud-g-qualified-federal-voterp p) (aud-g-protected-right-to-votep cs p) (aud-g-removal-transactionp p) (aud-g-statute-removes-registrantp law p) (not (aud-g-valid-regulationp law p))))

;; --- 18 audited propositions (1 encapsulate constraints, 17 defaxioms) ---
;; constraint government-removal-defense-rule  [mega_act_s113_government_model]
(defthm aud-g-government-removal-defense-rule
  (implies (and (aud-g-save-indicates-noncitizenp p) (aud-g-important-government-interestp law) (aud-g-removal-procedure-evenhandedp law) (aud-g-save-data-reliablep law)) (aud-g-government-removal-defense-establishedp law p))
  :rule-classes nil)
;; axiom text-s113-noncitizen-determination-removes  [mega_act_s113_text_rules]
(defthm aud-g-text-s113-noncitizen-determination-removes
  (implies (and (aud-g-personp p) (aud-g-registered-voterp p) (aud-g-determined-ineligible-noncitizenp p)) (aud-g-statute-removes-registrantp 'mega-act p))
  :rule-classes nil)
;; axiom text-s113-noncitizen-removal-at-any-time  [mega_act_s113_text_rules]
(defthm aud-g-text-s113-noncitizen-removal-at-any-time
  (implies (and (aud-g-personp p) (aud-g-determined-ineligible-noncitizenp p)) (aud-g-removable-at-any-timep p))
  :rule-classes nil)
;; axiom text-s113-residence-removal-requires-return-card  [mega_act_s113_text_rules]
(defthm aud-g-text-s113-residence-removal-requires-return-card
  (implies (and (aud-g-personp p) (aud-g-registered-voterp p) (aud-g-removed-for-residence-changep p)) (aud-g-notice-card-sentp p))
  :rule-classes nil)
;; axiom scenario-r-person  [mega_act_s113_scenario]
(defthm aud-g-scenario-r-person
  (aud-g-personp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-citizen  [mega_act_s113_scenario]
(defthm aud-g-scenario-r-citizen
  (aud-g-citizen-of-usp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-eligible  [mega_act_s113_scenario]
(defthm aud-g-scenario-r-eligible
  (aud-g-eligible-voterp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-registered  [mega_act_s113_scenario]
(defthm aud-g-scenario-r-registered
  (aud-g-registered-voterp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-save-indicates-noncitizen  [mega_act_s113_scenario]
(defthm aud-g-scenario-r-save-indicates-noncitizen
  (aud-g-save-indicates-noncitizenp 'registrant-r)
  :rule-classes nil)
;; axiom scenario-r-no-notice  [mega_act_s113_scenario]
(defthm aud-g-scenario-r-no-notice
  (not (aud-g-adequate-notice-before-removalp 'registrant-r))
  :rule-classes nil)
;; axiom scenario-r-no-hearing  [mega_act_s113_scenario]
(defthm aud-g-scenario-r-no-hearing
  (not (aud-g-opportunity-to-be-heardp 'registrant-r))
  :rule-classes nil)
;; axiom text-mega-act-is-law  [mega_act_s113_scenario]
(defthm aud-g-text-mega-act-is-law
  (aud-g-lawp 'mega-act)
  :rule-classes nil)
;; axiom semantic-b-determination-requires-notice  [mega_act_s113_hinge_process]
(defthm aud-g-semantic-b-determination-requires-notice
  (implies (not (aud-g-adequate-notice-before-removalp p)) (not (aud-g-determined-ineligible-noncitizenp p)))
  :rule-classes nil)
;; axiom government-bridge-removal-validates  [mega_act_s113_government_model]
(defthm aud-g-government-bridge-removal-validates
  (implies (aud-g-government-removal-defense-establishedp law p) (aud-g-valid-regulationp law p))
  :rule-classes nil)
;; axiom government-important-interest  [mega_act_s113_government_model]
(defthm aud-g-government-important-interest
  (aud-g-important-government-interestp 'mega-act)
  :rule-classes nil)
;; axiom government-removal-procedure-evenhanded  [mega_act_s113_government_model]
(defthm aud-g-government-removal-procedure-evenhanded
  (aud-g-removal-procedure-evenhandedp 'mega-act)
  :rule-classes nil)
;; axiom government-save-data-reliable  [mega_act_s113_government_model]
(defthm aud-g-government-save-data-reliable
  (aud-g-save-data-reliablep 'mega-act)
  :rule-classes nil)
;; axiom government-assume-right-to-vote-arguendo  [mega_act_s113_government_model]
(defthm aud-g-government-assume-right-to-vote-arguendo
  (aud-g-protected-right-to-votep 'amend-v-due-process 'registrant-r)
  :rule-classes nil)

;;; =========================================================================
;;; JOINT UNSATISFIABILITY of the two registration bridges (propositional):
;;; the challenger needs (not (valid-regulationp law x)) and the government
;;; needs (valid-regulationp law x) for the same application x.  No world
;;; satisfies both, which is why the party books are never loaded together.
;;; =========================================================================
(defthm parties-registration-bridges-jointly-unsatisfiable
  (not (and (implies ci (not v))   ; challenger-bridge-regulation-invalid
            (implies gd v)         ; government-bridge-defense-validates
            ci gd))
  :rule-classes nil)
