(in-package "ACL2")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; federal_save_act_core.lisp  —  v3 (encapsulate architecture)
;; Neutral legal vocabulary and generic conflict condition.
;; Generated by the Constitutional ACL2 Stress-Test Agent.
;;
;; This book defines uninterpreted predicates (defstub) and neutral
;; helper functions.  It does not contain any facts, interpretations,
;; or assumptions.  All models include this book.
;;
;; v3 changes (from v2):
;;   • Added presents-documentary-proofp (possession ≠ presentation)
;;   • Completed has-any-qualifying-documentp with birth cert + nat cert
;;   • Added factored intermediate predicates:
;;       qualified-federal-voterp, registration-transactionp,
;;       save-act-denial-triggerp
;;   • Added Mathis burden-severity stubs (neutral — both sides constrain)
;;   • Refactored constitutional-conflict-conditionp through intermediates
;;
;; Domain: Federal voter registration / documentary proof of citizenship
;; Constitutional provisions: Elections Clause (Art. I, §4),
;;   Equal Protection (Amend. XIV, §1 via Amend. V), Poll Tax (Amend. XXIV)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; =========================================================================
;;; Ontological predicates
;;; =========================================================================

(defstub personp (x) t)                        ; x is a person
(defstub lawp (x) t)                           ; x is a law/statute
(defstub citizen-of-usp (x) t)                 ; x is a citizen of the United States
(defstub eligible-voterp (x) t)                ; x is eligible to vote in federal elections
(defstub voter-registration-applicationp (x) t) ; x is a voter reg application

;;; =========================================================================
;;; Documentary proof predicates (NVRA § 3(b) as amended)
;;;
;;; v3 distinguishes POSSESSION from PRESENTATION:
;;;   has-documentary-proofp    — person possesses qualifying documents
;;;   presents-documentary-proofp — person presents documents WITH the
;;;                                  application (the statute's actual
;;;                                  requirement: "presents ... with the
;;;                                  application")
;;; =========================================================================

(defstub has-documentary-proofp (x) t)         ; x possesses documentary proof
(defstub presents-documentary-proofp (p x) t)  ; p presents proof with application x

;; Individual document-type predicates
(defstub has-real-id-indicating-citizenshipp (x) t)
(defstub has-valid-us-passportp (x) t)
(defstub has-military-id-with-us-birthp (x) t)
(defstub has-govt-photo-id-showing-us-birthp (x) t)
(defstub has-govt-photo-id-with-supporting-docp (x) t)
(defstub has-certified-birth-certificatep (x) t)
(defstub has-naturalization-certificatep (x) t)

;;; =========================================================================
;;; Constitutional predicates
;;; =========================================================================

(defstub protected-right-to-votep (constitution-section x) t)
  ;; x has a constitutionally protected right to vote under constitution-section

(defstub undue-burden-on-right-to-votep (law x) t)
  ;; law imposes an undue burden on x's right to vote

;;; =========================================================================
;;; Regulatory predicates
;;; =========================================================================

(defstub valid-regulationp (law x) t)
  ;; law is a constitutionally valid regulation of the activity/object x

(defstub statute-denies-registrationp (law p x) t)
  ;; law denies person p registration through application x

;;; =========================================================================
;;; Conduct / transaction verbs
;;; =========================================================================

(defstub attempts-to-registerp (p x) t)        ; p attempts to register via application x
(defstub registers-by-mailp (p x) t)           ; p registers via mail application x
(defstub registers-at-dmvp (p x) t)            ; p registers via motor-voter at DMV

;;; =========================================================================
;;; Alternative process predicates (NVRA § 8(j)(2)(A))
;;; =========================================================================

(defstub alternative-process-availablep (p x) t) ; alternative attestation process is available
(defstub alternative-process-approvedp (p x) t)  ; p approved via alternative process for app x
(defstub signs-attestation-under-perjuryp (p) t) ; p signs attestation under penalty of perjury
(defstub submits-other-evidencep (p) t)           ; p submits other evidence of citizenship
(defstub official-determines-citizenshipp (p) t)  ; official determines p is a citizen

;;; =========================================================================
;;; Removal predicates (NVRA § 8(k))
;;; =========================================================================

(defstub verified-noncitizen-informationp (p) t) ; verified info that p is not a citizen
(defstub adequate-notice-before-removalp (p) t)  ; p received adequate notice before removal
(defstub opportunity-to-be-heardp (p) t)          ; p had opportunity to contest removal

;;; =========================================================================
;;; Penalty predicates
;;; =========================================================================

(defstub criminal-penalty-for-official-assistancep (official) t)
(defstub criminal-penalty-for-registering-without-proofp (official p) t)

;;; =========================================================================
;;; Cost predicates (for poll-tax analysis)
;;; =========================================================================

(defstub document-acquisition-costp (p) t)     ; p must pay to obtain qualifying documents
(defstub cost-functions-as-poll-taxp (law p) t) ; the cost functions as a de facto poll tax

;;; =========================================================================
;;; Mathis / Anderson-Burdick burden-severity predicates
;;;
;;; These are NEUTRAL stubs.  Both the challenger and government models
;;; constrain them differently.  Placing them here lets the core and the
;;; generalized theorems reference them without importing interpretive
;;; content.
;;;
;;; Challenger-side (turned ON in challenger model):
;;;   substantial-risk-of-erroneous-denialp
;;;   severe-burden-on-plaintiffp
;;;   cannot-obtain-qualifying-documents-without-material-burdenp
;;;   alternative-process-discretionary-forp
;;;
;;; Government-side (turned ON in government model):
;;;   important-government-interestp
;;;   registration-procedure-evenhandedp
;;;   documentary-proof-requirement-rationally-connectedp
;;;   adequate-alternative-processp  (also used as neutral pred)
;;;   burden-not-severep
;;; =========================================================================

;; Challenger-side burden predicates
(defstub lacks-qualifying-documents-through-no-faultp (p) t)
(defstub cannot-obtain-qualifying-documents-without-material-burdenp (p) t)
(defstub alternative-process-discretionary-forp (p x) t)
(defstub substantial-risk-of-erroneous-denialp (law p) t)
(defstub severe-burden-on-plaintiffp (law p) t)

;; Government-side defense predicates
(defstub important-government-interestp (law) t)
(defstub election-integrity-interestp (law) t)
(defstub registration-procedure-evenhandedp (law) t)
(defstub documentary-proof-requirement-rationally-connectedp (law) t)
(defstub reasonable-registration-requirementp (law) t)
(defstub adequate-alternative-processp (law) t)
(defstub burden-not-severep (law p) t)

;;; =========================================================================
;;; Neutral helper functions
;;; =========================================================================

;; BRIDGE_RULE: A person has documentary proof if they possess any
;; qualifying document from the statutory list.
;; This is a neutral structural rule derived from NVRA § 3(b).
;;
;; v3 FIX: Now includes birth certificates and naturalization certificates,
;; which were declared as stubs in v2 but omitted from this disjunction.
(defun has-any-qualifying-documentp (p)
  (or (has-real-id-indicating-citizenshipp p)
      (has-valid-us-passportp p)
      (has-military-id-with-us-birthp p)
      (has-govt-photo-id-showing-us-birthp p)
      (has-govt-photo-id-with-supporting-docp p)
      (has-certified-birth-certificatep p)
      (has-naturalization-certificatep p)))

;;; =========================================================================
;;; Factored intermediate predicates (v3)
;;;
;;; Instead of one big final theorem relying on many axioms, v3
;;; introduces smaller intermediate propositions for ACL2 to reason
;;; over.  These are NEUTRAL structural compositions.
;;; =========================================================================

;; A person is a qualified federal voter if they are a person, a citizen,
;; and eligible.
(defun qualified-federal-voterp (p)
  (and (personp p)
       (citizen-of-usp p)
       (eligible-voterp p)))

;; A registration transaction occurs when a person attempts to register
;; via a voter registration application.
(defun registration-transactionp (p x)
  (and (personp p)
       (voter-registration-applicationp x)
       (attempts-to-registerp p x)))

;; The SAVE Act denial trigger fires when a person does not present
;; documentary proof with their application AND is not approved through
;; the alternative process.
;;
;; NOTE: This uses presents-documentary-proofp (not has-documentary-proofp)
;; because the statute requires presentation with the application, not
;; mere possession.
(defun save-act-denial-triggerp (p x)
  (and (registration-transactionp p x)
       (not (presents-documentary-proofp p x))
       (not (alternative-process-approvedp p x))))

;;; =========================================================================
;;; Generic constitutional conflict condition (v3 — factored)
;;;
;;; Pattern (composed from intermediate predicates):
;;;   1. The law is a law
;;;   2. The person is a qualified federal voter
;;;   3. The person has a constitutionally protected right to vote
;;;   4. The person attempts to register (registration transaction)
;;;   5. The statute denies that person's registration
;;;   6. The statute is NOT a valid regulation
;;; =========================================================================

(defun constitutional-conflict-conditionp (law constitution-section p x)
  (and (lawp law)
       (qualified-federal-voterp p)
       (protected-right-to-votep constitution-section p)
       (registration-transactionp p x)
       (statute-denies-registrationp law p x)
       (not (valid-regulationp law x))))
