(in-package "ACL2")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; federal_save_act_core.lisp
;; Neutral legal vocabulary and generic conflict condition.
;; Generated by the Constitutional ACL2 Stress-Test Agent.
;;
;; This book defines uninterpreted predicates (defstub) and neutral
;; helper functions. It does not contain any facts, interpretations,
;; or assumptions. All models include this book.
;;
;; Domain: Federal voter registration / documentary proof of citizenship
;; Constitutional provisions: Elections Clause (Art. I, §4),
;;   Equal Protection (Amend. XIV, §1), Poll Tax (Amend. XXIV)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; ---- Ontological predicates ----

(defstub personp (x) t)                        ; x is a person
(defstub lawp (x) t)                           ; x is a law/statute
(defstub citizen-of-usp (x) t)                 ; x is a citizen of the United States
(defstub eligible-voterp (x) t)                ; x is eligible to vote in federal elections
(defstub voter-registration-applicationp (x) t) ; x is a voter reg application

;;; ---- Documentary proof predicates (NVRA § 3(b) as amended) ----

(defstub has-documentary-proofp (x) t)         ; x possesses documentary proof of citizenship
(defstub has-real-id-indicating-citizenshipp (x) t)
(defstub has-valid-us-passportp (x) t)
(defstub has-military-id-with-us-birthp (x) t)
(defstub has-govt-photo-id-showing-us-birthp (x) t)
(defstub has-govt-photo-id-with-supporting-docp (x) t)
(defstub has-certified-birth-certificatep (x) t)
(defstub has-naturalization-certificatep (x) t)

;;; ---- Constitutional predicates ----

(defstub protected-right-to-votep (constitution-section x) t)
  ;; x has a constitutionally protected right to vote under constitution-section

(defstub undue-burden-on-right-to-votep (law x) t)
  ;; law imposes an undue burden on x's right to vote

;;; ---- Regulatory predicates ----

(defstub valid-regulationp (law x) t)
  ;; law is a constitutionally valid regulation of the activity/object x

(defstub statute-denies-registrationp (law p x) t)
  ;; law denies person p registration through application x

;;; ---- Conduct / transaction verbs ----

(defstub attempts-to-registerp (p x) t)        ; p attempts to register via application x
(defstub registers-by-mailp (p x) t)           ; p registers via mail application x
(defstub registers-at-dmvp (p x) t)            ; p registers via motor-voter at DMV
(defstub presents-documentary-proofp (p x) t)  ; p presents documentary proof with application x

;;; ---- Alternative process predicates (NVRA § 8(j)(2)(A)) ----

(defstub alternative-process-availablep (p x) t) ; alternative attestation process is available
(defstub alternative-process-approvedp (p x) t)  ; p approved via alternative process for app x
(defstub signs-attestation-under-perjuryp (p) t) ; p signs attestation under penalty of perjury
(defstub submits-other-evidencep (p) t)           ; p submits other evidence of citizenship
(defstub official-determines-citizenshipp (p) t)  ; official determines p is a citizen

;;; ---- Removal predicates (NVRA § 8(k)) ----

(defstub verified-noncitizen-informationp (p) t) ; verified info that p is not a citizen
(defstub adequate-notice-before-removalp (p) t)  ; p received adequate notice before removal
(defstub opportunity-to-be-heardp (p) t)          ; p had opportunity to contest removal

;;; ---- Penalty predicates ----

(defstub criminal-penalty-for-official-assistancep (official) t)
(defstub criminal-penalty-for-registering-without-proofp (official p) t)

;;; ---- Cost predicates (for poll-tax analysis) ----

(defstub document-acquisition-costp (p) t)     ; p must pay to obtain qualifying documents
(defstub cost-functions-as-poll-taxp (law p) t) ; the cost functions as a de facto poll tax

;;; ---- Neutral helper functions ----

;; BRIDGE_RULE: A person has documentary proof if they possess any
;; qualifying document from the statutory list.
;; This is a neutral structural rule derived from NVRA § 3(b).
(defun has-any-qualifying-documentp (p)
  (or (has-real-id-indicating-citizenshipp p)
      (has-valid-us-passportp p)
      (has-military-id-with-us-birthp p)
      (has-govt-photo-id-showing-us-birthp p)
      (has-govt-photo-id-with-supporting-docp p)))

;;; ---- Generic constitutional conflict condition ----
;; This is a neutral structural predicate. Whether its conditions are
;; satisfied depends on the interpretive model loaded.
;;
;; Pattern:
;;   1. The SAVE Act is a law
;;   2. Person is a person
;;   3. Person is a U.S. citizen eligible to vote
;;   4. Person has a constitutionally protected right to vote
;;   5. Person attempts to register for a federal election
;;   6. The statute denies that person's registration
;;   7. The statute is NOT a valid regulation

(defun constitutional-conflict-conditionp (law constitution-section p x)
  (and (lawp law)
       (personp p)
       (citizen-of-usp p)
       (eligible-voterp p)
       (protected-right-to-votep constitution-section p)
       (attempts-to-registerp p x)
       (statute-denies-registrationp law p x)
       (not (valid-regulationp law x))))
