#!/usr/bin/env python3
"""
print_axioms.py — the ACL2 analogue of Lean's `#print axioms` (cf. Vero § D,
"axiom allowlist"): for every book, compute the set of defaxioms in its
include-book closure.  Every theorem in a book can depend at most on the
axioms in that closure, so this is a sound (book-level) upper bound on each
theorem's trusted base.  Axioms are classified by their decider tag from
sources/clause_trace.csv.

Outputs reports/trusted_base_by_book.json and .md.  `--check` fails if the
committed report is stale.
"""
import csv, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "model"

def books():
    out = {}
    for f in sorted(list(MODEL.glob("*.lisp")) + list(MODEL.glob("lib/*.lisp"))):
        name = f.relative_to(MODEL).with_suffix("").as_posix()
        src = re.sub(r";[^\n]*", "", f.read_text(encoding="utf-8", errors="replace"))
        incs = re.findall(r'\(include-book\s+"([^"]+)"', src)
        axs = re.findall(r'^\s*\(defaxiom\s+([\w\-]+)', src, re.M)
        thms = re.findall(r'^\s*\(defthm\s+([\w\-]+)', src, re.M)
        out[name] = {"includes": incs, "axioms": axs, "theorems": thms}
    return out

def closure(b, info, seen=None):
    seen = seen if seen is not None else set()
    if b in seen or b not in info: return seen
    seen.add(b)
    for i in info[b]["includes"]:
        closure(i, info, seen)
    return seen

def main():
    info = books()
    deciders = {r["axiom_name"]: r["decider"] for r in csv.DictReader(open(ROOT / "sources/clause_trace.csv", encoding="utf-8-sig"))}
    report = {}
    for b in info:
        cl = closure(b, info)
        axs = sorted(a for c in cl for a in info[c]["axioms"])
        by = {}
        for a in axs:
            d = deciders.get(a, "untagged"); by[d] = by.get(d, 0) + 1
        report[b] = {"theorems": len(info[b]["theorems"]), "trusted_base": axs, "count": len(axs), "by_decider": by,
                     "theorem_names": info[b]["theorems"]}
    md = ["# Trusted base by book (ACL2 `#print axioms` analogue)", "",
          "Every theorem in a book depends on at most the defaxioms in the book's `include-book` closure. Generated by `tools/print_axioms.py`; checked in CI.", "",
          "| Book | Theorems | Axioms in closure | By decider |", "|---|---|---|---|"]
    for b, r in sorted(report.items(), key=lambda kv: (kv[1]["count"], kv[0])):
        by = ", ".join(f"{k} {v}" for k, v in sorted(r["by_decider"].items()))
        md.append(f"| `{b}` | {r['theorems']} | **{r['count']}** | {by or '—'} |")
    md += ["", "## Axiom-free books", "", ", ".join(f"`{b}`" for b, r in sorted(report.items()) if r["count"] == 0 and r["theorems"]), ""]
    (ROOT / "reports").mkdir(exist_ok=True)
    jpath, mpath = ROOT / "reports/trusted_base_by_book.json", ROOT / "reports/trusted_base_by_book.md"
    new_j = json.dumps(report, indent=2) + "\n"; new_m = "\n".join(md) + "\n"
    if "--check" in sys.argv:
        if (jpath.read_text() if jpath.exists() else None) != new_j or (mpath.read_text() if mpath.exists() else None) != new_m:
            print("STALE: reports/trusted_base_by_book.* — rerun tools/print_axioms.py"); return 1
        print("OK: trusted base report matches"); return 0
    jpath.write_text(new_j); mpath.write_text(new_m)
    clean = sum(1 for r in report.values() if r["count"] == 0 and r["theorems"])
    print(f"wrote reports/trusted_base_by_book.{{json,md}}: {len(report)} books, {clean} axiom-free books with theorems")
    return 0

if __name__ == "__main__":
    sys.exit(main())
